export const categories = {
  mixed: {
    name: "Mixed Bag",
    icon: "🎲",
    words: [
      "Pizza", "Elephant", "Basketball", "Guitar", "Astronaut", "Rainbow", "Volcano",
      "Skateboard", "Butterfly", "Thunderstorm", "Popcorn", "Penguin", "Helicopter",
      "Sunglasses", "Waterfall", "Rollercoaster", "Cactus", "Fireworks", "Ninja",
      "Telescope", "Trampoline", "Dinosaur", "Lighthouse", "Hammock", "Snowman",
      "Tornado", "Kangaroo", "Motorcycle", "Pyramid", "Microwave", "Dragon",
      "Saxophone", "Skyscraper", "Octopus", "Parachute", "Submarine", "Treasure",
      "Unicorn", "Wizard", "Zombie", "Campfire", "Surfboard", "Magazine", "Castle",
      "Dentist", "Elevator", "Flashlight", "Garden", "Hospital", "Iceberg",
      "Jellyfish", "Tornado", "Compass", "Backpack", "Umbrella", "Crown", "Diamond",
      "Pirate", "Robot", "Spaceship", "Rocket", "Comet", "Galaxy", "Planet",
      "Mountain", "Ocean", "Desert", "Forest", "Jungle", "Island", "Beach",
      "Cave", "Bridge", "Tunnel", "Tower", "Statue", "Monument", "Fountain",
      "Clock", "Watch", "Calendar", "Map", "Globe", "Flag", "Banner",
      "Kite", "Balloon", "Bubble", "Mirror", "Window", "Door", "Key",
      "Lock", "Chain", "Rope", "Ladder", "Stairs", "Escalator", "Slide",
      "Swing", "Seesaw", "Carousel", "Ferris Wheel", "Merry-Go-Round", "Bumper Cars",
      "Anchor", "Sailboat", "Yacht", "Cruise Ship", "Submarine", "Aircraft Carrier",
      "Train", "Locomotive", "Bullet Train", "Subway", "Metro", "Tram", "Trolley",
      "Bus", "Double Decker", "School Bus", "Tour Bus", "Shuttle", "Taxi", "Cab",
      "Car", "Sedan", "SUV", "Convertible", "Sports Car", "Truck", "Pickup",
      "Van", "Minivan", "RV", "Motorhome", "Ambulance", "Fire Truck", "Police Car",
      "Bicycle", "Bike", "Mountain Bike", "Road Bike", "Unicycle", "Tricycle", "Scooter",
      "Skateboard", "Longboard", "Roller Skates", "Rollerblades", "Hoverboard", "Segway",
      "Airplane", "Jet", "Helicopter", "Hot Air Balloon", "Zeppelin", "Blimp", "Glider",
      "Rocket Ship", "Space Shuttle", "Satellite", "Space Station", "Mars Rover", "Lunar Module",
      "Building", "House", "Mansion", "Cottage", "Cabin", "Igloo", "Tent",
      "Apartment", "Condominium", "Penthouse", "Studio", "Duplex", "Townhouse", "Villa",
      "Skyscraper", "Office Building", "Factory", "Warehouse", "Barn", "Silo", "Windmill",
      "School", "University", "Library", "Museum", "Theater", "Cinema", "Stadium",
      "Restaurant", "Cafe", "Diner", "Bar", "Pub", "Nightclub", "Casino",
      "Store", "Shop", "Market", "Mall", "Boutique", "Department Store", "Supermarket",
      "Bank", "Post Office", "Hospital", "Clinic", "Pharmacy", "Gas Station", "Parking Lot",
      "Park", "Playground", "Zoo", "Aquarium", "Botanical Garden", "Amusement Park", "Theme Park",
      "Beach", "Shore", "Coast", "Harbor", "Port", "Marina", "Pier",
      "Mountain", "Hill", "Valley", "Canyon", "Cliff", "Peak", "Summit",
      "River", "Stream", "Creek", "Lake", "Pond", "Ocean", "Sea",
      "Island", "Peninsula", "Archipelago", "Atoll", "Reef", "Lagoon", "Bay",
      "Forest", "Woods", "Jungle", "Rainforest", "Swamp", "Marsh", "Wetland",
      "Desert", "Oasis", "Dune", "Cactus", "Tumbleweed", "Mirage", "Sandstorm",
      "Animal", "Dog", "Cat", "Bird", "Fish", "Horse", "Cow",
      "Pig", "Sheep", "Goat", "Chicken", "Duck", "Rabbit", "Hamster",
      "Lion", "Tiger", "Bear", "Wolf", "Fox", "Deer", "Elk",
      "Monkey", "Ape", "Gorilla", "Chimpanzee", "Orangutan", "Baboon", "Lemur",
      "Snake", "Lizard", "Turtle", "Tortoise", "Crocodile", "Alligator", "Frog",
      "Shark", "Whale", "Dolphin", "Seal", "Walrus", "Sea Lion", "Otter",
      "Insect", "Butterfly", "Bee", "Ant", "Spider", "Beetle", "Dragonfly",
      "Flower", "Rose", "Tulip", "Sunflower", "Daisy", "Orchid", "Lily",
      "Tree", "Oak", "Pine", "Maple", "Birch", "Willow", "Palm",
      "Weather", "Sun", "Cloud", "Rain", "Snow", "Wind", "Storm",
      "Thunder", "Lightning", "Rainbow", "Tornado", "Hurricane", "Tsunami", "Earthquake",
      "Time", "Clock", "Watch", "Hourglass", "Calendar", "Schedule", "Appointment",
      "Day", "Night", "Morning", "Afternoon", "Evening", "Dawn", "Dusk",
      "Season", "Spring", "Summer", "Fall", "Winter", "Monsoon", "Dry Season",
      "Color", "Red", "Blue", "Green", "Yellow", "Orange", "Purple",
      "Pink", "Black", "White", "Gray", "Brown", "Gold", "Silver",
      "Shape", "Circle", "Square", "Triangle", "Rectangle", "Oval", "Diamond",
      "Star", "Heart", "Arrow", "Cross", "Plus", "Minus", "Equal"
    ]
  },
  popCulture: {
    name: "Pop Culture",
    icon: "🎬",
    words: [
      "Taylor Swift", "Beyoncé", "Spider-Man", "Harry Potter", "The Beatles", "Oprah Winfrey",
      "Star Wars", "Marvel", "Disney", "Netflix", "TikTok", "Instagram", "Fortnite",
      "Drake", "Lady Gaga", "Michael Jackson", "Super Bowl", "Oscars", "Grammy Awards",
      "Stranger Things", "Game of Thrones", "The Avengers", "Batman", "Iron Man",
      "Billie Eilish", "Ariana Grande", "The Weeknd", "Kanye West", "Rihanna",
      "Breaking Bad", "Friends", "The Office", "Squid Game", "Wednesday Addams",
      "Avatar", "Titanic", "Jurassic Park", "Pokémon", "Mario", "Minecraft",
      "Harry Styles", "Dwayne Johnson", "Tom Cruise", "Jennifer Lawrence", "Elon Musk",
      "LeBron James", "Cristiano Ronaldo", "Tom Brady", "Serena Williams", "Messi",
      "The Simpsons", "South Park", "Family Guy", "Rick and Morty", "The Walking Dead",
      "House of Cards", "Orange Is the New Black", "The Crown", "Bridgerton", "The Witcher",
      "The Mandalorian", "The Last of Us", "Among Us", "Call of Duty", "Grand Theft Auto",
      "Justin Bieber", "Ed Sheeran", "Bruno Mars", "Adele", "Coldplay", "Radiohead",
      "The Rolling Stones", "Queen", "AC/DC", "Metallica", "Nirvana", "Pearl Jam",
      "Eminem", "Jay-Z", "Kendrick Lamar", "Travis Scott", "Post Malone", "The Weeknd",
      "Dua Lipa", "Olivia Rodrigo", "Doja Cat", "Lizzo", "Megan Thee Stallion",
      "Black Panther", "Wonder Woman", "Superman", "Wonder Woman", "The Joker",
      "Iron Man", "Captain America", "Thor", "Hulk", "Black Widow", "Doctor Strange",
      "WandaVision", "Loki", "Falcon and Winter Soldier", "Hawkeye", "Moon Knight",
      "The Matrix", "Inception", "Interstellar", "The Dark Knight", "Pulp Fiction",
      "Forrest Gump", "The Shawshank Redemption", "Fight Club", "Goodfellas", "Scarface",
      "The Godfather", "Casino", "The Departed", "Heat", "The Usual Suspects",
      "Tiger King", "Making a Murderer", "The Queen's Gambit", "Squid Game", "Money Heist",
      "Cobra Kai", "Emily in Paris", "Lupin", "Dark", "The Boys", "Invincible",
      "The Sopranos", "The Wire", "Lost", "24", "Homeland", "Westworld", "True Detective",
      "Fargo", "Better Call Saul", "Ozark", "Succession", "Yellowstone", "1883", "1923",
      "The Handmaid's Tale", "The Crown", "The Crown", "Peaky Blinders", "Outlander", "Vikings",
      "The Last Kingdom", "Game of Thrones", "House of the Dragon", "The Witcher", "Shadow and Bone",
      "Wednesday", "Dahmer", "Dahmer", "Dahmer", "Dahmer", "Dahmer", "Dahmer",
      "The White Lotus", "Euphoria", "The Bear", "Only Murders in the Building", "Severance",
      "Ted Lasso", "Schitt's Creek", "The Good Place", "Parks and Recreation", "30 Rock",
      "Brooklyn Nine-Nine", "Modern Family", "How I Met Your Mother", "The Big Bang Theory",
      "Two and a Half Men", "Seinfeld", "Curb Your Enthusiasm", "Veep", "Silicon Valley",
      "Arrested Development", "It's Always Sunny in Philadelphia", "Community", "Scrubs",
      "Grey's Anatomy", "House", "ER", "Chicago Med", "The Good Doctor", "New Amsterdam",
      "Law & Order", "CSI", "NCIS", "Criminal Minds", "Bones", "Castle", "The Mentalist",
      "Sherlock", "Elementary", "Luther", "True Crime", "Making a Murderer", "The Jinx",
      "Serial", "My Favorite Murder", "Crime Junkie", "Dateline", "48 Hours", "20/20",
      "The Bachelor", "The Bachelorette", "Love Island", "Too Hot to Handle", "Love Is Blind",
      "Married at First Sight", "90 Day Fiancé", "The Real Housewives", "Keeping Up with the Kardashians",
      "The Kardashians", "KUWTK", "Selling Sunset", "Bling Empire", "Below Deck",
      "Survivor", "The Amazing Race", "Big Brother", "The Challenge", "The Circle",
      "Squid Game", "Physical: 100", "Single's Inferno", "Alice in Borderland", "All of Us Are Dead",
      "Sweet Home", "Kingdom", "Hellbound", "Extracurricular", "My Name",
      "The Glory", "Crash Landing on You", "Itaewon Class", "Vincenzo", "It's Okay to Not Be Okay",
      "Extraordinary Attorney Woo", "The Good Bad Mother", "Celebrity", "Mask Girl", "The Uncanny Counter",
      "Anime", "Naruto", "One Piece", "Dragon Ball Z", "Attack on Titan", "Demon Slayer",
      "My Hero Academia", "Death Note", "Fullmetal Alchemist", "Hunter x Hunter", "Bleach",
      "Jujutsu Kaisen", "Chainsaw Man", "Spy x Family", "Tokyo Ghoul", "Parasyte",
      "Studio Ghibli", "Spirited Away", "My Neighbor Totoro", "Howl's Moving Castle", "Princess Mononoke",
      "Akira", "Ghost in the Shell", "Cowboy Bebop", "Neon Genesis Evangelion", "Sailor Moon",
      "Pokémon", "Digimon", "Yu-Gi-Oh!", "Beyblade", "Bakugan", "Cardcaptor Sakura",
      "Video Games", "The Legend of Zelda", "Final Fantasy", "Metal Gear Solid", "Resident Evil",
      "Silent Hill", "The Last of Us", "Uncharted", "God of War", "Horizon Zero Dawn",
      "Assassin's Creed", "Watch Dogs", "Far Cry", "Just Cause", "Tomb Raider",
      "Tomb Raider", "Lara Croft", "Nathan Drake", "Kratos", "Aloy", "Ellie", "Joel",
      "Super Mario", "Sonic the Hedgehog", "Donkey Kong", "Kirby", "Metroid", "Star Fox",
      "Pac-Man", "Tetris", "Pong", "Space Invaders", "Galaga", "Centipede", "Asteroids",
      "Street Fighter", "Mortal Kombat", "Tekken", "Soulcalibur", "King of Fighters",
      "FIFA", "Madden NFL", "NBA 2K", "NHL", "MLB The Show", "WWE 2K", "UFC",
      "Racing Games", "Gran Turismo", "Forza", "Need for Speed", "Burnout", "Mario Kart",
      "RPG", "World of Warcraft", "Final Fantasy XIV", "Elder Scrolls", "Fallout", "Mass Effect",
      "Dragon Age", "The Witcher", "Dark Souls", "Bloodborne", "Elden Ring", "Sekiro",
      "Indie Games", "Minecraft", "Terraria", "Stardew Valley", "Hollow Knight", "Celeste",
      "Undertale", "Cuphead", "Ori and the Blind Forest", "Limbo", "Inside", "Little Nightmares",
      "Mobile Games", "Candy Crush", "Angry Birds", "Clash of Clans", "Pokémon GO", "Among Us",
      "Fall Guys", "Rocket League", "Apex Legends", "Valorant", "Overwatch", "Team Fortress 2",
      "Counter-Strike", "Call of Duty", "Battlefield", "Halo", "Gears of War", "Destiny",
      "Music", "Spotify", "Apple Music", "Pandora", "SoundCloud", "Bandcamp", "Tidal",
      "Radio", "Podcast", "Audiobook", "Streaming", "Download", "Playlist", "Album",
      "Single", "EP", "LP", "Vinyl", "CD", "Cassette", "8-Track",
      "Record Player", "Turntable", "Speaker", "Headphones", "Earbuds", "AirPods", "Beats",
      "Concert", "Festival", "Coachella", "Lollapalooza", "Bonnaroo", "Glastonbury", "Woodstock",
      "Grammy Awards", "MTV Video Music Awards", "Billboard Music Awards", "American Music Awards",
      "Country Music Awards", "BET Awards", "Latin Grammy Awards", "Juno Awards", "Brit Awards",
      "Movies", "Cinema", "Theater", "IMAX", "3D", "4DX", "Drive-In",
      "Oscars", "Academy Awards", "Golden Globes", "Emmys", "Tonys", "Grammys", "SAG Awards",
      "Film Festival", "Cannes", "Sundance", "Toronto", "Venice", "Berlin", "Tribeca",
      "Box Office", "Opening Weekend", "Gross", "Blockbuster", "Bomb", "Flop", "Hit",
      "Trailer", "Teaser", "Poster", "Premiere", "Red Carpet", "After Party", "Press Tour",
      "Director", "Producer", "Screenwriter", "Cinematographer", "Editor", "Composer", "Actor",
      "Actress", "Star", "Celebrity", "A-Lister", "B-List", "C-List", "D-List",
      "Fame", "Fortune", "Wealth", "Luxury", "Yacht", "Private Jet", "Mansion",
      "Paparazzi", "Tabloid", "Gossip", "Scandal", "Controversy", "Rumor", "Leak",
      "Social Media", "Viral", "Trending", "Hashtag", "Meme", "Influencer", "Content Creator",
      "YouTube", "TikTok", "Instagram", "Twitter", "Facebook", "Snapchat", "Pinterest",
      "LinkedIn", "Reddit", "Discord", "Twitch", "OnlyFans", "Patreon", "Substack",
      "Blog", "Vlog", "Podcast", "Livestream"
    ]
  },
  history: {
    name: "History",
    icon: "📜",
    words: [
      "Abraham Lincoln", "George Washington", "Winston Churchill", "Napoleon Bonaparte",
      "Julius Caesar", "Cleopatra", "Martin Luther King Jr", "Rosa Parks", "Albert Einstein",
      "Leonardo da Vinci", "Christopher Columbus", "Marco Polo", "Joan of Arc",
      "Alexander the Great", "Genghis Khan", "Benjamin Franklin", "Thomas Edison",
      "Wright Brothers", "Neil Armstrong", "Amelia Earhart", "World War II", "Civil War",
      "American Revolution", "French Revolution", "Cold War", "Great Depression",
      "Industrial Revolution", "Renaissance", "Ancient Egypt", "Roman Empire",
      "Ancient Greece", "Pyramids", "Great Wall of China", "Colosseum", "Taj Mahal",
      "Declaration of Independence", "Constitution", "Magna Carta", "Berlin Wall",
      "Titanic", "Pearl Harbor", "D-Day", "Apollo 11", "Salem Witch Trials",
      "Boston Tea Party", "Gold Rush", "Oregon Trail", "Wild West", "Vikings",
      "Thomas Jefferson", "John F. Kennedy", "Franklin D. Roosevelt", "Theodore Roosevelt",
      "Gandhi", "Nelson Mandela", "Malcolm X", "Harriet Tubman", "Sojourner Truth",
      "Susan B. Anthony", "Elizabeth Cady Stanton", "Marie Curie", "Galileo Galilei",
      "Isaac Newton", "Charles Darwin", "Louis Pasteur", "Alexander Graham Bell",
      "Henry Ford", "Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Jeff Bezos",
      "Ancient Rome", "Byzantine Empire", "Ottoman Empire", "British Empire", "Mongol Empire",
      "Persian Empire", "Maya Civilization", "Aztec Empire", "Inca Empire", "Ancient China",
      "Medieval Times", "The Crusades", "Black Death", "The Reformation", "The Enlightenment",
      "World War I", "Vietnam War", "Korean War", "Gulf War", "War on Terror",
      "The Holocaust", "Atomic Bomb", "Cuban Missile Crisis", "Fall of Berlin Wall",
      "9/11", "Moon Landing", "First Flight", "First Computer", "Internet",
      "Stonehenge", "Machu Picchu", "Easter Island", "Angkor Wat", "Petra",
      "Sphinx", "Parthenon", "Acropolis", "Versailles", "Buckingham Palace",
      "White House", "Statue of Liberty", "Mount Rushmore", "Golden Gate Bridge",
      "Eiffel Tower", "Big Ben", "Leaning Tower of Pisa", "Sagrada Familia",
      "John Adams", "James Madison", "James Monroe", "Andrew Jackson", "Ulysses S. Grant",
      "Woodrow Wilson", "Calvin Coolidge", "Herbert Hoover", "Harry S. Truman", "Dwight D. Eisenhower",
      "John F. Kennedy", "Lyndon B. Johnson", "Richard Nixon", "Gerald Ford", "Jimmy Carter",
      "Ronald Reagan", "George H. W. Bush", "Bill Clinton", "George W. Bush", "Barack Obama",
      "Donald Trump", "Joe Biden", "Kamala Harris", "Hillary Clinton", "Bernie Sanders",
      "Vladimir Putin", "Xi Jinping", "Kim Jong-un", "Angela Merkel", "Emmanuel Macron",
      "Boris Johnson", "Rishi Sunak", "Justin Trudeau", "Jair Bolsonaro", "Narendra Modi",
      "Ancient History", "Prehistory", "Stone Age", "Bronze Age", "Iron Age", "Classical Antiquity",
      "Middle Ages", "Dark Ages", "Renaissance", "Age of Discovery", "Age of Enlightenment",
      "Industrial Age", "Modern Era", "Contemporary History", "Post-Modern", "Information Age",
      "Ancient Civilizations", "Mesopotamia", "Sumer", "Babylon", "Assyria", "Persia",
      "Phoenicia", "Carthage", "Ancient Israel", "Judah", "Philistia", "Moab", "Edom",
      "Ancient India", "Indus Valley", "Vedic Period", "Maurya Empire", "Gupta Empire",
      "Ancient China", "Shang Dynasty", "Zhou Dynasty", "Qin Dynasty", "Han Dynasty",
      "Tang Dynasty", "Song Dynasty", "Ming Dynasty", "Qing Dynasty", "Republic of China",
      "Ancient Japan", "Jomon Period", "Yayoi Period", "Kofun Period", "Asuka Period",
      "Nara Period", "Heian Period", "Kamakura Period", "Muromachi Period", "Edo Period",
      "Ancient Korea", "Three Kingdoms", "Goryeo", "Joseon", "Korean Empire",
      "Southeast Asia", "Khmer Empire", "Srivijaya", "Majapahit", "Ayutthaya",
      "African Empires", "Ancient Egypt", "Nubia", "Kush", "Axum", "Ghana", "Mali",
      "Songhai", "Zimbabwe", "Great Zimbabwe", "Swahili Coast", "Ethiopia",
      "Pre-Columbian Americas", "Olmec", "Maya", "Aztec", "Inca", "Moche", "Nazca",
      "Anasazi", "Cahokia", "Mississippian", "Iroquois", "Cherokee", "Apache", "Sioux",
      "European History", "Celts", "Gauls", "Germanic Tribes", "Vandals", "Goths", "Visigoths",
      "Ostrogoths", "Franks", "Anglo-Saxons", "Vikings", "Normans", "Slavs", "Magyars",
      "Medieval Europe", "Holy Roman Empire", "Byzantine Empire", "Venetian Republic", "Genoese Republic",
      "Kingdom of France", "Kingdom of England", "Kingdom of Spain", "Kingdom of Portugal",
      "Kingdom of Scotland", "Kingdom of Ireland", "Kingdom of Poland", "Grand Duchy of Lithuania",
      "Rus'", "Kievan Rus'", "Novgorod Republic", "Muscovy", "Russian Empire",
      "Islamic History", "Rashidun Caliphate", "Umayyad Caliphate", "Abbasid Caliphate",
      "Fatimid Caliphate", "Ayyubid Dynasty", "Mamluk Sultanate", "Ottoman Empire",
      "Safavid Empire", "Mughal Empire", "Almoravid Empire", "Almohad Caliphate",
      "Renaissance", "Italian Renaissance", "Northern Renaissance", "High Renaissance",
      "Protestant Reformation", "Counter-Reformation", "Thirty Years' War", "Wars of Religion",
      "Age of Exploration", "Voyages of Discovery", "Columbian Exchange", "Spice Trade",
      "Colonialism", "Imperialism", "Scramble for Africa", "Partition of Africa",
      "American Colonies", "Thirteen Colonies", "New France", "New Spain", "New Netherlands",
      "Colonial America", "Jamestown", "Plymouth", "Massachusetts Bay", "Pennsylvania",
      "Revolutionary Period", "American Revolution", "French Revolution", "Haitian Revolution",
      "Latin American Revolutions", "Mexican War of Independence", "South American Wars of Independence",
      "Napoleonic Wars", "Coalition Wars", "Peninsular War", "Hundred Days", "Waterloo",
      "Congress of Vienna", "Concert of Europe", "Balance of Power", "Metternich System",
      "Industrial Revolution", "First Industrial Revolution", "Second Industrial Revolution",
      "Steam Engine", "Railway", "Telegraph", "Telephone", "Electricity", "Internal Combustion",
      "World War I", "Central Powers", "Allied Powers", "Western Front", "Eastern Front",
      "Gallipoli", "Verdun", "Somme", "Ypres", "Marne", "Tannenberg",
      "Russian Revolution", "February Revolution", "October Revolution", "Russian Civil War",
      "Treaty of Versailles", "League of Nations", "Interwar Period", "Roaring Twenties",
      "Great Depression", "Dust Bowl", "New Deal", "Fascism", "Nazism", "Communism",
      "World War II", "Axis Powers", "Allies", "Blitzkrieg", "Battle of Britain",
      "Operation Barbarossa", "Pearl Harbor", "D-Day", "Operation Overlord", "Battle of Stalingrad",
      "Battle of Midway", "Battle of Guadalcanal", "Iwo Jima", "Okinawa", "Hiroshima", "Nagasaki",
      "Holocaust", "Final Solution", "Concentration Camp", "Auschwitz", "Treblinka", "Dachau",
      "Cold War", "Iron Curtain", "Berlin Blockade", "Berlin Airlift", "Korean War",
      "Vietnam War", "Cuban Missile Crisis", "Bay of Pigs", "Space Race", "Arms Race",
      "Détente", "Perestroika", "Glasnost", "Fall of Berlin Wall", "Dissolution of USSR",
      "Post-Cold War", "Gulf War", "Yugoslav Wars", "Rwandan Genocide", "9/11 Attacks",
      "War on Terror", "Iraq War", "Afghanistan War", "Arab Spring", "Syrian Civil War",
      "Historical Events", "Black Death", "Plague", "Pandemic", "Epidemic", "Spanish Flu",
      "Great Fire of London", "Great Chicago Fire", "San Francisco Earthquake", "Hurricane Katrina",
      "Historical Figures", "Philosophers", "Socrates", "Plato", "Aristotle", "Confucius",
      "Laozi", "Buddha", "Jesus Christ", "Muhammad", "Martin Luther", "John Calvin",
      "Scientists", "Copernicus", "Kepler", "Galileo", "Newton", "Darwin", "Einstein",
      "Curie", "Tesla", "Edison", "Bell", "Wright Brothers", "Armstrong", "Gagarin",
      "Artists", "Michelangelo", "Raphael", "Leonardo", "Van Gogh", "Picasso", "Monet",
      "Renoir", "Degas", "Cézanne", "Matisse", "Dali", "Warhol", "Pollock",
      "Writers", "Shakespeare", "Dante", "Homer", "Virgil", "Goethe", "Tolstoy",
      "Dostoevsky", "Dickens", "Twain", "Hemingway", "Fitzgerald", "Orwell", "Tolkien",
      "Composers", "Bach", "Mozart", "Beethoven", "Chopin", "Tchaikovsky", "Wagner",
      "Historical Documents", "Magna Carta", "Declaration of Independence", "Constitution",
      "Bill of Rights", "Gettysburg Address", "Emancipation Proclamation", "Treaty of Versailles",
      "Historical Places", "Seven Wonders", "Great Pyramid", "Hanging Gardens", "Temple of Artemis",
      "Statue of Zeus", "Mausoleum", "Colossus of Rhodes", "Lighthouse of Alexandria",
      "Modern Wonders", "Chichen Itza", "Christ the Redeemer", "Great Wall", "Machu Picchu",
      "Petra", "Taj Mahal", "Colosseum", "Great Wall of China", "Forbidden City",
      "Historical Periods", "Paleolithic", "Neolithic", "Bronze Age", "Iron Age",
      "Classical Period", "Hellenistic Period", "Roman Republic", "Roman Empire"
    ]
  },
  food: {
    name: "Food & Drink",
    icon: "🍕",
    words: [
      "Cheeseburger", "Sushi", "Tacos", "Spaghetti", "Pancakes", "Ice Cream", "Chocolate",
      "Coffee", "Coca-Cola", "Starbucks", "McDonald's", "Pizza Hut", "Subway",
      "Cheesecake", "Brownies", "Cookies", "Donuts", "Croissant", "Bagel", "Muffin",
      "Chicken Wings", "French Fries", "Nachos", "Popcorn", "Hot Dog", "Pretzel",
      "Milkshake", "Smoothie", "Lemonade", "Orange Juice", "Energy Drink", "Tea",
      "Bacon", "Eggs", "Cereal", "Toast", "Sandwich", "Burrito", "Quesadilla",
      "Ramen", "Pho", "Pad Thai", "Curry", "Dumplings", "Spring Rolls", "Sashimi",
      "Barbecue", "Steak", "Lobster", "Shrimp",
      "Pasta", "Lasagna", "Ravioli", "Penne", "Fettuccine", "Macaroni", "Carbonara",
      "Pizza", "Margherita", "Pepperoni", "Hawaiian", "Supreme", "Meat Lovers",
      "Salad", "Caesar Salad", "Greek Salad", "Cobb Salad", "Waldorf Salad",
      "Soup", "Chicken Noodle", "Tomato Soup", "Clam Chowder", "French Onion", "Minestrone",
      "Sandwich", "BLT", "Club Sandwich", "Reuben", "Philly Cheesesteak", "Grilled Cheese",
      "Breakfast", "Waffles", "French Toast", "Omelet", "Scrambled Eggs", "Benedict",
      "Dessert", "Pie", "Apple Pie", "Pumpkin Pie", "Cherry Pie", "Key Lime Pie",
      "Cake", "Birthday Cake", "Chocolate Cake", "Cheesecake", "Red Velvet", "Carrot Cake",
      "Ice Cream", "Vanilla", "Chocolate", "Strawberry", "Mint Chip", "Rocky Road",
      "Candy", "Gummy Bears", "Chocolate Bar", "Lollipop", "Jelly Beans", "M&Ms",
      "Fruit", "Apple", "Banana", "Orange", "Strawberry", "Blueberry", "Watermelon",
      "Vegetable", "Broccoli", "Carrot", "Spinach", "Lettuce", "Tomato", "Cucumber",
      "Meat", "Chicken", "Beef", "Pork", "Lamb", "Turkey", "Duck",
      "Seafood", "Salmon", "Tuna", "Crab", "Mussels", "Oysters", "Squid",
      "Beverage", "Water", "Soda", "Juice", "Beer", "Wine", "Cocktail",
      "Wine", "Red Wine", "White Wine", "Champagne", "Prosecco", "Rosé",
      "Beer", "IPA", "Lager", "Stout", "Pilsner", "Wheat Beer",
      "Coffee", "Espresso", "Cappuccino", "Latte", "Americano", "Macchiato",
      "Fast Food", "Burger", "Fries", "Nuggets", "Taco", "Burrito", "Wrap",
      "Italian Food", "Risotto", "Gnocchi", "Polenta", "Osso Buco", "Bruschetta", "Caprese",
      "Margherita Pizza", "Neapolitan Pizza", "Calzone", "Stromboli", "Focaccia", "Breadstick",
      "Alfredo", "Marinara", "Pesto", "Bolognese", "Arrabbiata", "Puttanesca", "Carbonara",
      "French Food", "Coq au Vin", "Bouillabaisse", "Ratatouille", "Cassoulet", "Confit",
      "Escargot", "Foie Gras", "Duck à l'Orange", "Beef Bourguignon", "Quiche", "Croque Monsieur",
      "Crêpe", "Soufflé", "Mousse", "Crème Brûlée", "Éclair", "Macaron", "Madeleine",
      "Asian Cuisine", "Chinese Food", "Kung Pao Chicken", "General Tso's Chicken", "Sweet and Sour",
      "Orange Chicken", "Beef and Broccoli", "Mongolian Beef", "Mapo Tofu", "Peking Duck",
      "Dim Sum", "Dumpling", "Xiaolongbao", "Char Siu Bao", "Har Gow", "Siu Mai", "Turnip Cake",
      "Japanese Food", "Tempura", "Teriyaki", "Yakitori", "Okonomiyaki", "Takoyaki", "Tonkatsu",
      "Katsu Curry", "Udon", "Soba", "Miso Soup", "Edamame", "Gyoza", "Onigiri",
      "Bento Box", "Sashimi", "Nigiri", "Maki Roll", "California Roll", "Dragon Roll", "Spider Roll",
      "Thai Food", "Tom Yum", "Tom Kha", "Pad See Ew", "Pad Kee Mao", "Massaman Curry", "Green Curry",
      "Red Curry", "Yellow Curry", "Panang Curry", "Som Tam", "Larb", "Satay",
      "Vietnamese Food", "Bánh Mì", "Bún Bò Huế", "Bún Chả", "Gỏi Cuốn", "Phở Gà", "Bánh Xèo",
      "Korean Food", "Kimchi", "Bulgogi", "Galbi", "Bibimbap", "Japchae", "Tteokbokki",
      "Korean BBQ", "Samgyeopsal", "Jjigae", "Sundubu Jjigae", "Doenjang Jjigae", "Kimchi Jjigae",
      "Indian Food", "Butter Chicken", "Tikka Masala", "Biryani", "Rogan Josh", "Vindaloo", "Korma",
      "Samosas", "Pakora", "Naan", "Roti", "Paratha", "Dosa", "Idli",
      "Tandoori", "Chana Masala", "Dal", "Palak Paneer", "Aloo Gobi", "Baingan Bharta",
      "Mexican Food", "Enchiladas", "Chiles Rellenos", "Mole", "Carnitas", "Al Pastor", "Barbacoa",
      "Chimichanga", "Tostada", "Torta", "Elote", "Esquites", "Guacamole", "Salsa",
      "Pico de Gallo", "Queso", "Queso Fundido", "Churros", "Flan", "Tres Leches", "Horchata",
      "Mediterranean Food", "Hummus", "Baba Ganoush", "Tzatziki", "Tabbouleh", "Fattoush", "Falafel",
      "Shawarma", "Gyro", "Kebab", "Döner", "Spanakopita", "Moussaka", "Pastitsio",
      "Greek Salad", "Greek Yogurt", "Feta Cheese", "Olives", "Pita Bread", "Baklava", "Loukoumades",
      "Middle Eastern Food", "Couscous", "Tagine", "Shakshuka", "Baba Ganoush", "Labneh", "Za'atar",
      "Persian Food", "Kebab", "Chelo Kebab", "Ghormeh Sabzi", "Fesenjan", "Tahdig", "Baklava",
      "Seafood Dishes", "Fish and Chips", "Lobster Roll", "Crab Cake", "Clam Chowder", "Oysters Rockefeller",
      "Ceviche", "Poke Bowl", "Fish Tacos", "Bouillabaisse", "Paella", "Jambalaya", "Gumbo",
      "Sushi Varieties", "Tuna Roll", "Salmon Roll", "Eel Roll", "Shrimp Tempura Roll", "Rainbow Roll",
      "Spicy Tuna", "Spicy Salmon", "Dragon Roll", "Caterpillar Roll", "Spider Roll", "Volcano Roll",
      "Breakfast Foods", "Oatmeal", "Granola", "Yogurt", "Parfait", "Smoothie Bowl", "Acai Bowl",
      "Breakfast Burrito", "Breakfast Sandwich", "Bagel and Lox", "Smoked Salmon", "Avocado Toast",
      "Eggs Benedict", "Eggs Florentine", "Shakshuka", "Huevos Rancheros", "Chilaquiles", "Frittata",
      "Quiche Lorraine", "Quiche Florentine", "Breakfast Casserole", "French Toast Casserole",
      "Desserts", "Tiramisu", "Cannoli", "Gelato", "Sorbet", "Sherbet", "Frozen Yogurt",
      "Pudding", "Flan", "Crème Caramel", "Panna Cotta", "Bread Pudding", "Rice Pudding", "Tapioca",
      "Cookies", "Chocolate Chip", "Oatmeal Raisin", "Sugar Cookie", "Snickerdoodle", "Peanut Butter",
      "Shortbread", "Biscotti", "Macaron", "Madeleine", "Fortune Cookie", "Oreo", "Fig Newton",
      "Cakes", "Angel Food Cake", "Pound Cake", "Bundt Cake", "Coffee Cake", "Spice Cake", "Fruitcake",
      "Icebox Cake", "Ice Cream Cake", "Tres Leches", "Tiramisu", "Opera Cake", "Black Forest",
      "Pies", "Pecan Pie", "Lemon Meringue", "Banana Cream", "Coconut Cream", "Chocolate Cream",
      "Buttermilk Pie", "Shoofly Pie", "Sweet Potato Pie", "Rhubarb Pie", "Strawberry Rhubarb",
      "Beverages", "Lemonade", "Iced Tea", "Sweet Tea", "Arnold Palmer", "Mojito", "Mint Julep",
      "Sangria", "Mimosa", "Bellini", "Bloody Mary", "Margarita", "Daiquiri", "Piña Colada",
      "Cocktails", "Old Fashioned", "Manhattan", "Martini", "Cosmopolitan", "Moscow Mule", "Negroni",
      "Whiskey Sour", "Tom Collins", "Gin and Tonic", "Rum and Coke", "Screwdriver", "Cape Cod",
      "Wine Varieties", "Cabernet Sauvignon", "Merlot", "Pinot Noir", "Syrah", "Malbec", "Zinfandel",
      "Chardonnay", "Sauvignon Blanc", "Pinot Grigio", "Riesling", "Moscato", "Prosecco", "Champagne",
      "Beer Styles", "Pale Ale", "India Pale Ale", "Double IPA", "Stout", "Porter", "Wheat Beer",
      "Pilsner", "Lager", "Amber Ale", "Brown Ale", "Sour Beer", "Belgian Ale", "Hefeweizen",
      "Coffee Drinks", "Frappuccino", "Cold Brew", "Nitro Cold Brew", "Affogato", "Cortado", "Flat White",
      "Red Eye", "Black Eye", "Dead Eye", "Café au Lait", "Café Mocha", "White Chocolate Mocha",
      "Tea Varieties", "Green Tea", "Black Tea", "Oolong Tea", "White Tea", "Earl Grey", "English Breakfast",
      "Chai", "Matcha", "Jasmine Tea", "Peppermint Tea", "Chamomile Tea", "Hibiscus Tea", "Rooibos",
      "Snacks", "Chips", "Pretzels", "Popcorn", "Nuts", "Trail Mix", "Granola Bar",
      "Protein Bar", "Energy Bar", "Crackers", "Cheese and Crackers", "Veggie Sticks", "Hummus and Pita",
      "Dips", "Ranch", "Blue Cheese", "French Onion", "Spinach Artichoke", "Buffalo Chicken", "Queso",
      "Salsa", "Guacamole", "Hummus", "Tzatziki", "Baba Ganoush", "Pimento Cheese", "Crab Dip",
      "Cheeses", "Cheddar", "Swiss", "Mozzarella", "Parmesan", "Brie", "Camembert",
      "Gouda", "Havarti", "Provolone", "Pepper Jack", "Monterey Jack", "Blue Cheese", "Gorgonzola",
      "Goat Cheese", "Feta", "Ricotta", "Cottage Cheese", "Cream Cheese", "Mascarpone", "Burrata",
      "Spices and Herbs", "Salt", "Pepper", "Garlic", "Onion", "Basil", "Oregano",
      "Thyme", "Rosemary", "Sage", "Parsley", "Cilantro", "Dill", "Mint",
      "Cumin", "Coriander", "Turmeric", "Ginger", "Cinnamon", "Nutmeg", "Paprika",
      "Chili Powder", "Cayenne", "Red Pepper Flakes", "Bay Leaves", "Star Anise", "Cardamom", "Cloves",
      "Cooking Methods", "Grilled", "Roasted", "Baked", "Fried", "Sautéed", "Steamed",
      "Boiled", "Poached", "Braised", "Stewed", "Smoked", "Barbecued", "Marinated",
      "Restaurant Types", "Fine Dining", "Casual Dining", "Fast Casual", "Food Truck", "Café", "Bistro",
      "Brasserie", "Trattoria", "Osteria", "Tavern", "Pub", "Gastropub", "Steakhouse",
      "Seafood Restaurant", "Sushi Bar", "Ramen Shop", "Taco Stand", "Pizzeria", "Bakery", "Deli",
      "Fast Food Chains", "Burger King", "Wendy's", "Taco Bell", "KFC", "Popeyes", "Chick-fil-A",
      "In-N-Out", "Five Guys", "Shake Shack", "Chipotle", "Qdoba", "Panera Bread", "Subway",
      "Domino's", "Papa John's", "Little Caesars", "Pizza Hut", "Olive Garden", "Red Lobster", "Outback",
      "Applebee's", "TGI Friday's", "Chili's", "Buffalo Wild Wings", "Hooters", "Dave & Buster's"
    ]
  },
  sports: {
    name: "Sports & Games",
    icon: "⚽",
    words: [
      "Super Bowl", "World Cup", "Olympics", "March Madness", "World Series",
      "NBA Finals", "Stanley Cup", "Wimbledon", "Masters Tournament", "Tour de France",
      "Boxing", "Wrestling", "MMA", "Karate", "Judo", "Taekwondo", "Fencing",
      "Swimming", "Diving", "Gymnastics", "Track and Field", "Marathon", "Triathlon",
      "Volleyball", "Beach Volleyball", "Badminton", "Table Tennis", "Tennis",
      "Golf", "Bowling", "Billiards", "Darts", "Archery", "Skateboarding",
      "Snowboarding", "Skiing", "Ice Skating", "Hockey", "Lacrosse", "Rugby",
      "Cricket", "Baseball", "Softball", "Soccer", "Football", "Basketball",
      "Surfing", "Rock Climbing", "Cheerleading", "Yoga",
      "Athlete", "Player", "Coach", "Referee", "Umpire", "Team", "Captain",
      "Stadium", "Arena", "Field", "Court", "Rink", "Track", "Pool",
      "Equipment", "Ball", "Bat", "Racket", "Stick", "Club", "Helmet",
      "Uniform", "Jersey", "Cleats", "Sneakers", "Gloves", "Pads",
      "Baseball", "Home Run", "Strikeout", "Pitch", "Catcher", "Pitcher", "Batter",
      "Basketball", "Slam Dunk", "Three Pointer", "Free Throw", "Rebound", "Assist",
      "Football", "Touchdown", "Field Goal", "Interception", "Quarterback", "Running Back",
      "Soccer", "Goal", "Penalty", "Corner Kick", "Goalkeeper", "Striker",
      "Tennis", "Ace", "Serve", "Volley", "Backhand", "Forehand", "Match Point",
      "Golf", "Hole in One", "Eagle", "Birdie", "Par", "Bogey", "Tee",
      "Swimming", "Freestyle", "Backstroke", "Breaststroke", "Butterfly", "Medley",
      "Olympics", "Gold Medal", "Silver Medal", "Bronze Medal", "Olympic Torch",
      "World Cup", "FIFA", "Champions League", "Premier League", "La Liga",
      "NFL", "NHL", "MLB", "NBA", "MLS", "NASCAR", "Formula One",
      "LeBron James", "Michael Jordan", "Kobe Bryant", "Tom Brady", "Serena Williams",
      "Lionel Messi", "Cristiano Ronaldo", "Tiger Woods", "Roger Federer", "Usain Bolt",
      "Extreme Sports", "BMX", "Motocross", "Parkour", "Free Running", "Base Jumping",
      "Water Sports", "Water Polo", "Rowing", "Canoeing", "Kayaking", "Sailing",
      "Winter Sports", "Bobsled", "Luge", "Curling", "Biathlon", "Cross Country Skiing",
      "Baseball Terms", "Inning", "Strike", "Ball", "Walk", "Hit", "Double",
      "Triple", "Grand Slam", "No-Hitter", "Perfect Game", "Save", "Relief Pitcher",
      "Closer", "Designated Hitter", "Pinch Hitter", "Pinch Runner", "Steal", "Bunt",
      "Basketball Terms", "Jump Shot", "Layup", "Hook Shot", "Fadeaway", "Alley-Oop",
      "Pick and Roll", "Fast Break", "Full Court Press", "Zone Defense", "Man-to-Man",
      "Shot Clock", "Buzzer Beater", "And-One", "Technical Foul", "Flagrant Foul",
      "Football Terms", "First Down", "Second Down", "Third Down", "Fourth Down", "Punt",
      "Kickoff", "Field Goal", "Extra Point", "Two-Point Conversion", "Safety", "Fumble",
      "Sack", "Blitz", "Hail Mary", "Screen Pass", "Draw Play", "Play Action",
      "Soccer Terms", "Offside", "Corner Kick", "Free Kick", "Penalty Kick", "Yellow Card",
      "Red Card", "Hat Trick", "Clean Sheet", "Own Goal", "Nutmeg", "Bicycle Kick",
      "Tennis Terms", "Love", "Deuce", "Advantage", "Break Point", "Set Point", "Match Point",
      "Tiebreak", "Double Fault", "Let", "Out", "Fault", "Service", "Return",
      "Golf Terms", "Driver", "Iron", "Wedge", "Putter", "Fairway", "Rough",
      "Bunker", "Sand Trap", "Water Hazard", "Out of Bounds", "Mulligan", "Fore",
      "Swimming Terms", "Freestyle", "Backstroke", "Breaststroke", "Butterfly", "Individual Medley",
      "Relay", "Flip Turn", "Dive", "Lane", "Starting Block", "Touch Pad",
      "Olympic Sports", "Track and Field", "Long Jump", "High Jump", "Pole Vault", "Triple Jump",
      "Shot Put", "Discus", "Javelin", "Hammer Throw", "Decathlon", "Heptathlon",
      "100 Meter Dash", "200 Meter", "400 Meter", "800 Meter", "1500 Meter", "5000 Meter",
      "10000 Meter", "Marathon", "Hurdles", "Steeplechase", "Race Walk", "Relay Race",
      "Combat Sports", "Boxing", "Wrestling", "Judo", "Karate", "Taekwondo", "Fencing",
      "MMA", "UFC", "Boxing Ring", "Octagon", "Round", "Knockout", "Submission",
      "TKO", "Decision", "Unanimous Decision", "Split Decision", "Draw", "No Contest",
      "Water Sports", "Swimming", "Diving", "Synchronized Swimming", "Water Polo", "Surfing",
      "Windsurfing", "Kitesurfing", "Wakeboarding", "Water Skiing", "Jet Skiing", "Sailing",
      "Rowing", "Canoeing", "Kayaking", "Rafting", "Scuba Diving", "Snorkeling",
      "Winter Sports", "Skiing", "Alpine Skiing", "Cross Country Skiing", "Ski Jumping",
      "Snowboarding", "Halfpipe", "Slopestyle", "Ice Skating", "Figure Skating", "Speed Skating",
      "Hockey", "Ice Hockey", "Field Hockey", "Bobsled", "Skeleton", "Luge",
      "Curling", "Biathlon", "Nordic Combined", "Ski Mountaineering", "Ice Climbing",
      "Extreme Sports", "Skateboarding", "BMX", "Motocross", "Mountain Biking", "Rock Climbing",
      "Bouldering", "Free Climbing", "Base Jumping", "Skydiving", "Paragliding", "Hang Gliding",
      "Parkour", "Free Running", "Street Luge", "Downhill Mountain Biking", "Freestyle Skiing",
      "Team Sports", "Basketball", "Baseball", "Football", "Soccer", "Hockey", "Volleyball",
      "Beach Volleyball", "Rugby", "Lacrosse", "Cricket", "Water Polo", "Handball",
      "Individual Sports", "Tennis", "Golf", "Swimming", "Track and Field", "Gymnastics",
      "Boxing", "Wrestling", "Martial Arts", "Archery", "Shooting", "Equestrian",
      "Famous Athletes", "Michael Jordan", "LeBron James", "Kobe Bryant", "Magic Johnson",
      "Larry Bird", "Shaquille O'Neal", "Kareem Abdul-Jabbar", "Wilt Chamberlain", "Bill Russell",
      "Tom Brady", "Peyton Manning", "Joe Montana", "Jerry Rice", "Walter Payton",
      "Barry Sanders", "Lawrence Taylor", "Ray Lewis", "Deion Sanders", "Randy Moss",
      "Lionel Messi", "Cristiano Ronaldo", "Pelé", "Diego Maradona", "Zinedine Zidane",
      "Ronaldinho", "Ronaldo", "Neymar", "Kylian Mbappé", "Erling Haaland",
      "Serena Williams", "Venus Williams", "Roger Federer", "Rafael Nadal", "Novak Djokovic",
      "Pete Sampras", "Andre Agassi", "Steffi Graf", "Martina Navratilova", "Chris Evert",
      "Tiger Woods", "Jack Nicklaus", "Arnold Palmer", "Phil Mickelson", "Rory McIlroy",
      "Usain Bolt", "Carl Lewis", "Jesse Owens", "Florence Griffith Joyner", "Allyson Felix",
      "Michael Phelps", "Mark Spitz", "Katie Ledecky", "Missy Franklin", "Ryan Lochte",
      "Muhammad Ali", "Mike Tyson", "Floyd Mayweather", "Manny Pacquiao", "Sugar Ray Leonard",
      "Major Leagues", "NFL", "NBA", "MLB", "NHL", "MLS", "WNBA",
      "Premier League", "La Liga", "Serie A", "Bundesliga", "Ligue 1", "Champions League",
      "Europa League", "World Cup", "Euro Cup", "Copa América", "AFCON", "Asian Cup",
      "Olympic Games", "Summer Olympics", "Winter Olympics", "Paralympics", "Special Olympics",
      "Olympic Rings", "Olympic Flame", "Olympic Village", "Olympic Stadium", "Medal Ceremony",
      "Sports Venues", "Stadium", "Arena", "Coliseum", "Field", "Court", "Rink",
      "Pitch", "Track", "Pool", "Gymnasium", "Velodrome", "Aquatics Center",
      "Famous Venues", "Madison Square Garden", "Wembley Stadium", "Camp Nou", "Old Trafford",
      "Yankee Stadium", "Fenway Park", "Wrigley Field", "Lambeau Field", "Arrowhead Stadium",
      "Rose Bowl", "Superdome", "AT&T Stadium", "SoFi Stadium", "Mercedes-Benz Stadium",
      "Sports Equipment", "Ball", "Bat", "Racket", "Stick", "Club", "Helmet",
      "Pads", "Gloves", "Cleats", "Sneakers", "Jersey", "Uniform", "Whistle",
      "Stopwatch", "Scoreboard", "Net", "Goal", "Basket", "Hoop", "Pole",
      "Sports Positions", "Quarterback", "Running Back", "Wide Receiver", "Tight End",
      "Offensive Line", "Defensive Line", "Linebacker", "Cornerback", "Safety",
      "Point Guard", "Shooting Guard", "Small Forward", "Power Forward", "Center",
      "Pitcher", "Catcher", "First Base", "Second Base", "Shortstop", "Third Base",
      "Goalkeeper", "Defender", "Midfielder", "Forward", "Striker", "Winger",
      "Sports Events", "Super Bowl", "World Series", "NBA Finals", "Stanley Cup",
      "World Cup", "Olympics", "Wimbledon", "US Open", "French Open", "Australian Open",
      "Masters Tournament", "PGA Championship", "US Open Golf", "British Open",
      "March Madness", "Final Four", "NCAA Tournament", "College Football Playoff",
      "Sports Terms", "Championship", "Playoff", "Semifinal", "Final", "Champion",
      "Runner-Up", "MVP", "All-Star", "Hall of Fame", "Retirement", "Comeback",
      "Injury", "Recovery", "Training", "Practice", "Workout", "Conditioning",
      "Sports Statistics", "Points", "Goals", "Assists", "Rebounds", "Steals", "Blocks",
      "Touchdowns", "Home Runs", "Strikeouts", "Wins", "Losses", "Ties", "Record",
      "Sports Media", "ESPN", "SportsCenter", "NFL Network", "NBA TV", "MLB Network",
      "Sports Radio", "Podcast", "Commentary", "Play-by-Play", "Color Commentator",
      "Sports Betting", "Odds", "Spread", "Over/Under", "Parlay", "Prop Bet", "Futures",
      "Fantasy Sports", "Fantasy Football", "Fantasy Baseball", "Fantasy Basketball",
      "Draft", "Waiver Wire", "Trade", "Free Agent", "Injury Report", "Lineup"
    ]
  },
  technology: {
    name: "Technology",
    icon: "💻",
    words: [
      "iPhone", "Samsung", "Google", "Amazon", "Apple", "Microsoft", "Tesla",
      "Facebook", "Twitter", "YouTube", "Snapchat", "WhatsApp", "Zoom", "Spotify",
      "PlayStation", "Xbox", "Nintendo Switch", "Virtual Reality", "Artificial Intelligence",
      "Laptop", "Desktop", "Tablet", "Smartwatch", "AirPods", "Headphones",
      "Smartphone", "Bluetooth", "WiFi", "5G", "Internet", "Email", "Text Message",
      "Video Call", "Social Media", "Streaming", "Cloud Storage", "Password",
      "Keyboard", "Mouse", "Touchscreen", "Camera", "Selfie", "Screenshot",
      "USB Drive", "Hard Drive", "Processor", "Graphics Card", "Gaming PC",
      "Smart Home", "Alexa", "Siri", "Robot Vacuum", "Drone", "3D Printer",
      "App", "Application", "Software", "Operating System", "Windows", "macOS", "Linux",
      "iOS", "Android", "Chrome", "Safari", "Firefox", "Edge", "Browser",
      "Website", "Webpage", "URL", "Domain", "Server", "Hosting", "Cloud",
      "Database", "Server", "API", "Backend", "Frontend", "Full Stack", "Developer",
      "Programming", "Code", "Algorithm", "Bug", "Debug", "Update", "Patch",
      "Virus", "Malware", "Firewall", "Antivirus", "Encryption", "Security",
      "Bitcoin", "Cryptocurrency", "Blockchain", "NFT", "Ethereum", "Crypto",
      "Streaming", "Netflix", "Hulu", "Disney Plus", "HBO Max", "Prime Video",
      "Podcast", "Audiobook", "E-book", "Kindle", "iPad", "Surface",
      "Gaming", "PC Gaming", "Console", "Controller", "Headset", "Microphone",
      "Webcam", "Monitor", "Display", "Screen", "Resolution", "4K", "HD",
      "Battery", "Charger", "Cable", "Adapter", "Port", "USB-C", "Lightning",
      "Cloud", "iCloud", "Google Drive", "Dropbox", "OneDrive", "Backup",
      "Social Network", "Instagram", "TikTok", "LinkedIn", "Pinterest", "Reddit",
      "Messaging", "iMessage", "Slack", "Discord", "Telegram", "Signal",
      "E-commerce", "Online Shopping", "Delivery", "Amazon Prime", "eBay", "Etsy",
      "Navigation", "GPS", "Google Maps", "Waze", "Uber", "Lyft",
      "Smart Device", "IoT", "Wearable", "Fitness Tracker", "Smart TV", "Smart Speaker",
      "Machine Learning", "Deep Learning", "Neural Network", "Data Science", "Big Data",
      "Startup", "Silicon Valley", "Tech Company", "Innovation", "Disruption",
      "Programming Languages", "Python", "JavaScript", "Java", "C++", "C#", "Ruby",
      "Go", "Rust", "Swift", "Kotlin", "PHP", "TypeScript", "HTML", "CSS",
      "SQL", "R", "MATLAB", "Scala", "Perl", "Haskell", "Lua", "Dart",
      "Web Development", "React", "Vue", "Angular", "Node.js", "Express", "Django",
      "Flask", "Ruby on Rails", "Laravel", "Spring", "ASP.NET", "Next.js", "Nuxt",
      "Mobile Development", "React Native", "Flutter", "Xamarin", "Ionic", "Cordova",
      "iOS Development", "SwiftUI", "UIKit", "Xcode", "Android Development", "Android Studio",
      "Kotlin", "Jetpack Compose", "Material Design", "App Store", "Google Play",
      "Cloud Computing", "AWS", "Azure", "Google Cloud", "Heroku", "DigitalOcean",
      "Vercel", "Netlify", "Cloudflare", "Docker", "Kubernetes", "Container", "Microservices",
      "DevOps", "CI/CD", "Jenkins", "GitHub Actions", "GitLab CI", "Travis CI", "CircleCI",
      "Version Control", "Git", "GitHub", "GitLab", "Bitbucket", "SVN", "Mercurial",
      "Database", "MySQL", "PostgreSQL", "MongoDB", "Redis", "Cassandra", "Elasticsearch",
      "SQLite", "Oracle", "SQL Server", "DynamoDB", "Firebase", "Supabase", "Prisma",
      "Cybersecurity", "Encryption", "SSL", "TLS", "HTTPS", "VPN", "Proxy",
      "Two-Factor Authentication", "Biometric", "Fingerprint", "Face ID", "Password Manager",
      "Antivirus", "Malware", "Phishing", "Ransomware", "DDoS", "Firewall", "Intrusion Detection",
      "Penetration Testing", "Ethical Hacking", "Bug Bounty", "Security Audit", "Zero-Day",
      "Artificial Intelligence", "AI", "Machine Learning", "Deep Learning", "Neural Network",
      "Natural Language Processing", "NLP", "Computer Vision", "Reinforcement Learning",
      "ChatGPT", "GPT", "OpenAI", "Claude", "Bard", "LLM", "Transformer",
      "Data Science", "Data Analytics", "Data Mining", "Big Data", "Hadoop", "Spark",
      "Pandas", "NumPy", "TensorFlow", "PyTorch", "Scikit-learn", "Jupyter", "Notebook",
      "Blockchain", "Bitcoin", "Ethereum", "Cryptocurrency", "NFT", "Smart Contract",
      "DeFi", "Web3", "Metaverse", "Crypto Wallet", "Mining", "Proof of Work", "Proof of Stake",
      "Hardware", "CPU", "GPU", "RAM", "SSD", "HDD", "Motherboard", "Power Supply",
      "Graphics Card", "NVIDIA", "AMD", "Intel", "Apple Silicon", "M1", "M2", "M3",
      "Processor", "Chip", "Semiconductor", "Moore's Law", "Overclocking", "Cooling",
      "Peripherals", "Keyboard", "Mouse", "Monitor", "Webcam", "Microphone", "Speaker",
      "Printer", "Scanner", "External Hard Drive", "USB Flash Drive", "SD Card",
      "Networking", "Router", "Modem", "Switch", "Ethernet", "WiFi", "Bluetooth",
      "5G", "4G", "LTE", "Fiber Optic", "Cable", "DSL", "ISP",
      "Protocols", "TCP/IP", "HTTP", "HTTPS", "FTP", "SSH", "SMTP", "POP3", "IMAP",
      "DNS", "DHCP", "VPN", "TCP", "UDP", "ICMP", "ARP",
      "Operating Systems", "Windows", "macOS", "Linux", "Ubuntu", "Debian", "Fedora",
      "CentOS", "Red Hat", "Arch Linux", "Android", "iOS", "Chrome OS",
      "Software", "Application", "App", "Program", "Firmware", "Driver", "Kernel",
      "Open Source", "Proprietary", "Freeware", "Shareware", "SaaS", "PaaS", "IaaS",
      "Tech Companies", "Apple", "Microsoft", "Google", "Amazon", "Meta", "Facebook",
      "Tesla", "Netflix", "Uber", "Airbnb", "Twitter", "X", "LinkedIn",
      "Adobe", "Oracle", "IBM", "Intel", "NVIDIA", "AMD", "Qualcomm",
      "Salesforce", "Shopify", "Square", "Stripe", "PayPal", "Zoom", "Slack",
      "Tech Products", "iPhone", "iPad", "MacBook", "iMac", "Apple Watch", "AirPods",
      "Surface", "Xbox", "PlayStation", "Nintendo Switch", "Oculus", "Quest",
      "Gaming", "PC Gaming", "Console Gaming", "Mobile Gaming", "Esports", "Streaming",
      "Twitch", "YouTube Gaming", "Steam", "Epic Games", "Battle.net", "Origin",
      "Game Engine", "Unity", "Unreal Engine", "Godot", "GameMaker", "CryEngine",
      "Social Media", "Instagram", "TikTok", "Snapchat", "Pinterest", "Reddit", "Discord",
      "Clubhouse", "BeReal", "Mastodon", "Bluesky", "Threads", "LinkedIn", "Twitter",
      "Messaging Apps", "WhatsApp", "Telegram", "Signal", "iMessage", "WeChat", "Line",
      "Viber", "Skype", "Teams", "Slack", "Discord", "Zoom", "FaceTime",
      "E-commerce", "Amazon", "eBay", "Etsy", "Shopify", "WooCommerce", "Magento",
      "Online Payment", "PayPal", "Stripe", "Square", "Venmo", "Apple Pay", "Google Pay",
      "Cryptocurrency Exchange", "Coinbase", "Binance", "Kraken", "Gemini", "FTX",
      "Streaming Services", "Netflix", "Hulu", "Disney Plus", "HBO Max", "Prime Video",
      "Apple TV+", "Paramount+", "Peacock", "Showtime", "Starz", "Crunchyroll",
      "Music Streaming", "Spotify", "Apple Music", "Amazon Music", "YouTube Music", "Pandora",
      "SoundCloud", "Tidal", "Deezer", "Bandcamp", "iHeartRadio",
      "Podcast Platforms", "Apple Podcasts", "Spotify Podcasts", "Google Podcasts", "Stitcher",
      "Overcast", "Pocket Casts", "Anchor", "Podbean",
      "Productivity Tools", "Microsoft Office", "Google Workspace", "Notion", "Evernote",
      "Trello", "Asana", "Monday.com", "Jira", "Confluence", "Airtable", "ClickUp",
      "Design Software", "Photoshop", "Illustrator", "Figma", "Sketch", "InDesign",
      "Premiere Pro", "After Effects", "Final Cut Pro", "DaVinci Resolve", "Canva",
      "Code Editors", "VS Code", "Sublime Text", "Atom", "Vim", "Emacs", "IntelliJ",
      "WebStorm", "PyCharm", "Android Studio", "Xcode", "Eclipse", "NetBeans",
      "Tech Trends", "Metaverse", "Web3", "NFT", "Cryptocurrency", "Blockchain",
      "AI", "Machine Learning", "Quantum Computing", "Edge Computing", "IoT", "5G",
      "Augmented Reality", "AR", "Virtual Reality", "VR", "Mixed Reality", "MR",
      "Tech Terms", "Algorithm", "API", "Backend", "Frontend", "Full Stack", "DevOps",
      "Agile", "Scrum", "Sprint", "Kanban", "Waterfall", "CI/CD", "Microservices",
      "REST", "GraphQL", "JSON", "XML", "YAML", "Markdown", "Git", "Commit",
      "Branch", "Merge", "Pull Request", "Fork", "Clone", "Repository", "Deploy"
    ]
  }
};

